### PR TITLE
Feat: ModelController

### PR DESCRIPTION
**Pull request by eadwinCode**
# New Feature
### ModelController
- Create a new ModelControllerBase type to easily manage django models. Something similar to DRF ModelViewSet

```python
from ninja_extra import (
      api_controller, 
      ModelControllerBase, 
      http_post, 
      ModelConfig, 
      ModelSchemaConfig, 
      ModelEndpointFactory
)
from .models import Post
from . import schemas

@api_controller('/posts')
class PostController(ModelControllerBase):
    model_config = ModelConfig(
        model=Post,
        schema_config=ModelSchemaConfig(
            # include=[],
            # exclude=[],
            read_only_fields=['date_created', 'date_modified', 'publish_date', 'published', 'id'],
            # write_only_fields=[]
        ),
        # retrieve_schema=schemas.PostSchema,
        # create_schema=schemas.CreatePostSchema,
        # update_schema=schemas.PatchPostSchema,
        allowed_routes=['update', 'list', 'find_one', 'patch']
    )

    @http_post('/', response={201: schemas.PostSchema})
    def create_item(self, data: schemas.CreatePostSchema):
        # this will override default create_item endpoint
        return data.dict()

    list_post_tags = ModelEndpointFactory.list(
        path="/{int:post_id}/tags?query=int&query1=int",
        schema_out=schemas.TagSchema,
        queryset_getter=lambda self,**n: self.list_post_tags_query(**n)
    )

    def list_post_tags_query(self, **kwargs):
        assert 'query1' in kwargs
        post_id = kwargs['post_id']
        return Post.objects.filter(id=post_id).first().tags.all()




api = NinjaExtraAPI(title='ModelController Test')
api.register_controllers(PostController)
```
- ModelController usage will depend on [`ninja-schema`](https://github.com/eadwinCode/ninja-schema) for schema generation
image

### CODE REVIEW

**Comment by freemindcore** [comment]
Nice feature. 
Interestingly I wrote a similar thing, it will automatically scan Django-apps and create [Nestjs-CRUD](https://github.com/nestjsx/crud)  like APIs for each models. It will create schema based on Meta configurations.

```
@api_controller("events", permissions=[BaseApiPermission])
class EventControllerAPI(BaseAdminAPIController):
    def __init__(self, service: EventService):
        super().__init__(service)
        self.service = service

    class Meta:
        model = Event
        exclude = ["update_time", "create_time"]

    @http_get("/crud_get_objs_all", summary="crud_get_objs_all unittest")
    @paginate
    async def get_objs_all_with_filters(self, request, maximum: int = None, **filters):
        await self.service.dummy_biz_logics()
        await self.service.demo_action(data="running /get_objs_all_with_filters")
        return await self.service.get_objs(maximum, **filters)
```

**Comment by freemindcore** [comment]
I spend some time and put those codes together, still in early stage, comments and advices are highly appreciated.

https://github.com/freemindcore/django-api-framework
- Auto Async API generation for all django models, configurable
- Domain/Service/Controller base structure for better code organization
- Base Permission class and more to come

Thanks

**Comment by eadwinCode** [comment]
WOW, this is awesome. I have checked out the [https://github.com/freemindcore/django-api-framework](https://github.com/freemindcore/django-api-framework). What you have build was the initial idea for django-ninja-extra before I branched of to build [ellar](https://github.com/eadwinCode/ellar). If you enjoy NestJS, then you will definitely enjoy `ellar`.

For this feature, I intend to go with DRF Serializer approach,
having Schema fields defined in Meta in `fields`, `exclude`, `read_only` and `write_only` attributes. That way, CRUD schema will be fully defined. 

I will still look deep into your project or even contribute to it. I love the idea. Good job!!

**Comment by freemindcore** [comment]
Great! Looking forward to your advices or contributions.

Now I get to understand why you started [ellar](https://github.com/eadwinCode/ellar) project. I love [ellar](https://github.com/eadwinCode/ellar) too. It is a huge effort writing it from scratch on your own. Python is becoming more and more popular in server-side web development, I am sure Ellar sort of new framework will become a super star in the future!

Please keep up the good work!

**Pull request merged**
